// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PageDocumentDataSlicesSlice =
  | HeroSlice
  | HeaderSlice
  | SiteSlice
  | LinktreeSlice
  | RichTextSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

export type AllDocumentTypes = PageDocument;

/**
 * Item in *Header → Default → Primary → BotoesDeNavegacao*
 */
export interface HeaderSliceDefaultPrimaryBotoesdenavegacaoItem {
  /**
   * Nome da buttao field in *Header → Default → Primary → BotoesDeNavegacao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.botoesdenavegacao[].nome_da_buttao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome_da_buttao: prismic.KeyTextField;

  /**
   * link do buttao field in *Header → Default → Primary → BotoesDeNavegacao*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.botoesdenavegacao[].link_do_buttao
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_do_buttao: prismic.KeyTextField;
}

/**
 * Primary content in *Header → Default → Primary*
 */
export interface HeaderSliceDefaultPrimary {
  /**
   * Numero do telefone field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.numero_do_telefone
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  numero_do_telefone: prismic.KeyTextField;

  /**
   * Link do numero field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.link_do_numero
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_do_numero: prismic.KeyTextField;

  /**
   * insta field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.insta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  insta: prismic.KeyTextField;

  /**
   * Link do insta field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.link_do_insta
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_do_insta: prismic.KeyTextField;

  /**
   * horario de atendimento field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.horario_de_atendimento
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  horario_de_atendimento: prismic.KeyTextField;

  /**
   * cidade field in *Header → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.cidade
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cidade: prismic.KeyTextField;

  /**
   * logo field in *Header → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Cor Header field in *Header → Default → Primary*
   *
   * - **Field Type**: Color
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.cor_header
   * - **Documentation**: https://prismic.io/docs/field#color
   */
  cor_header: prismic.ColorField;

  /**
   * BotoesDeNavegacao field in *Header → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: header.default.primary.botoesdenavegacao[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  botoesdenavegacao: prismic.GroupField<
    Simplify<HeaderSliceDefaultPrimaryBotoesdenavegacaoItem>
  >;
}

/**
 * Default variation for Header Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeaderSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Header*
 */
type HeaderSliceVariation = HeaderSliceDefault;

/**
 * Header Shared Slice
 *
 * - **API ID**: `header`
 * - **Description**: Header
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeaderSlice = prismic.SharedSlice<"header", HeaderSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * imagem de fundo HeroSection web field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.imagem_de_fundo_herosection_web
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_de_fundo_herosection_web: prismic.ImageField<never>;

  /**
   * imagem de fundo HeroSection mobile field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.imagem_de_fundo_herosection_mobile
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem_de_fundo_herosection_mobile: prismic.ImageField<never>;

  /**
   * textoPrincipal field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Texto para deixar em destaque
   * - **API ID Path**: hero.default.primary.textoprincipal
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textoprincipal: prismic.KeyTextField;

  /**
   * texto para falar do lugar field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.texto_para_falar_do_lugar
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  texto_para_falar_do_lugar: prismic.RichTextField;

  /**
   * whatsapp field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.whatsapp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  whatsapp: prismic.KeyTextField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *Linktree → Default → Primary → Links*
 */
export interface LinktreeSliceDefaultPrimaryLinksItem {
  /**
   * TextoLink field in *Linktree → Default → Primary → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.default.primary.links[].textolink
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  textolink: prismic.KeyTextField;

  /**
   * Link Do Texto field in *Linktree → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.default.primary.links[].link_do_texto
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_do_texto: prismic.LinkField;
}

/**
 * Primary content in *Linktree → Default → Primary*
 */
export interface LinktreeSliceDefaultPrimary {
  /**
   * Foto field in *Linktree → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.default.primary.foto
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  foto: prismic.ImageField<never>;

  /**
   * Nome field in *Linktree → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.default.primary.nome
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  nome: prismic.KeyTextField;

  /**
   * Clinica Estetica field in *Linktree → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.default.primary.clinica_estetica
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  clinica_estetica: prismic.KeyTextField;

  /**
   * Links field in *Linktree → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: linktree.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<LinktreeSliceDefaultPrimaryLinksItem>>;
}

/**
 * Default variation for Linktree Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinktreeSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<LinktreeSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Linktree*
 */
type LinktreeSliceVariation = LinktreeSliceDefault;

/**
 * Linktree Shared Slice
 *
 * - **API ID**: `linktree`
 * - **Description**: Linktree
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LinktreeSlice = prismic.SharedSlice<
  "linktree",
  LinktreeSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * Content field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum...
   * - **API ID Path**: rich_text.default.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *Site → Default → Primary*
 */
export interface SiteSliceDefaultPrimary {
  /**
   * imagem field in *Site → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: site.default.primary.imagem
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  imagem: prismic.ImageField<never>;

  /**
   * texto field in *Site → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site.default.primary.texto
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  texto: prismic.KeyTextField;
}

/**
 * Default variation for Site Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SiteSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SiteSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Site*
 */
type SiteSliceVariation = SiteSliceDefault;

/**
 * Site Shared Slice
 *
 * - **API ID**: `site`
 * - **Description**: Site
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SiteSlice = prismic.SharedSlice<"site", SiteSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      AllDocumentTypes,
      HeaderSlice,
      HeaderSliceDefaultPrimaryBotoesdenavegacaoItem,
      HeaderSliceDefaultPrimary,
      HeaderSliceVariation,
      HeaderSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      LinktreeSlice,
      LinktreeSliceDefaultPrimaryLinksItem,
      LinktreeSliceDefaultPrimary,
      LinktreeSliceVariation,
      LinktreeSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SiteSlice,
      SiteSliceDefaultPrimary,
      SiteSliceVariation,
      SiteSliceDefault,
    };
  }
}
