// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  linktree: dynamic(() => import("./Linktree")),
  rich_text: dynamic(() => import("./RichText")),
};
