// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  header: dynamic(() => import("./Site")),
  hero: dynamic(() => import("./Hero")),
  linktree: dynamic(() => import("./Linktree")),
  rich_text: dynamic(() => import("./RichText")),
};
